### ISSUE TITLE
support for 1.20

### ISSUE THREAD

**Issue by FAKHORII** [bl4sterino/Elytra-Drag#1]
will this mod receive a 1.20 version also?

**Comment by bl4sterino** [comment]
I uploaded a version compabible with 1.20

**Comment by bl4sterino** [comment]
I uploaded a version compabible with 1.20

**Comment by FAKHORII** [comment]
> I uploaded a version compabible with 1.20

Thank u so much sir, wish u a lovely day, take care of u <3
