### ISSUE TITLE
Mod doesn't respect it's own config file (Incompatibility?)

### ISSUE THREAD

**Issue by SabrCat** [bl4sterino/Elytra-Drag#2]
Hi there! I've been testing the mod, and found the drag and minimum speed set a bit too extreme, so I tried changing them in the config file. However, changing them appears to have no effect in game even with a game restart.
The mod continues to behave as if the default configs were set. Might this be an incompatibility somewhere?
I will include a log below:

[QbGh3a9.txt](https://github.com/bl4sterino/Elytra-Drag/files/15180675/QbGh3a9.txt)

**Comment by bl4sterino** [comment]
Thank you very much for pointing that out !

I updated the mod to fix the issue, let me know if you encounter any problems.

**Comment by SabrCat** [comment]
Config appears to work now, thank you for the fix!
